Feat/openmedia hotstandby heartbeat logic
nrkno/sofie-mos-connection pull request #105
Opened 2024-10-08 07:43 UTC by olzzon

## About the Contributor
This is a PR made on behalf of BBC

## Type of Contribution

This is a Feature

## Current Behavior
Currently MOS-connection checks for heartbeat on all devices.

## New Behavior
There has been added an option `openMediaHotStandby?: boolean` in the API
When set to true, the heartbeat will be enabled/disabled depending on what OpenMedia server is being used.

## Testing Instructions
For test a dual OpenMedia server setup is needed, and openMediaHotStandby must be set on the secondary connection in deviceOptions.
```
deviceOptions.secondary.openMediaHotStandby = true
const mosDevice: MosDevice = await this.mos.connect(deviceOptions)
```

## Other Information

## Status

- [ ] PR is ready to be reviewed.
- [ ] The functionality has been tested by the author.
- [ ] Relevant unit tests has been added / updated.
- [ ] Relevant documentation (code comments, [system documentation](https://nrkno.github.io/sofie-core/)) has been added / updated.

2024-10-17 09:47 UTC, olzzon commented
Converted the PR to upstream from Draft to Ready be reviewed/merged

2024-10-21 06:31 UTC, nytamin requested changes
I'm missing a few things in this one to be able to merge it.

Mainly I'm missing unit tests covering this situation, and the `mosDevice.getConnectionStatus()` is not updated/defined how it should work.

I've added a (failing) unit test in the branch [chore/pr-105](https://github.com/nrkno/sofie-mos-connection/tree/chore/pr-105) to highlight some of the issues, please have a look at it and feel free merge it into your branch.

Also I have a question regarding the OpenMedia server: When the secondary server is standing by, does it accept any Socket connections still, or is it completely offline? (This is relevant to designing the unit test properly).

2024-10-28 09:39 UTC, olzzon commented on packages/connector/src/MosConnection.ts
> +							primary.enableHeartbeats()
The .on('connectionChanged'....) will still work, and if the primary is reconnected it will reset the heartbeats.

2024-11-12 10:04 UTC, mint-dewit commented
I've added some commits to this PR to better reflect what this feature entails. Specifically clarifying that the connection status report for the individual connections should still reflect the actual status of the system. 

I am open to adding a method that exposes a single status for both primary and secondary connection but if we are reporting the individual connections we should not add a "fake" connected status. That smells of bad magic. The user of the lib is already aware of the system being a "hot standby" and should interpret the status of the secondary accordingly.

2024-12-05 09:56 UTC, nytamin approved these changes

2024-12-05 09:58 UTC, nytamin commented
Yeah the "bad magic" would be good to avoid. I'm happy to merge this PR now.

2024-12-05 09:58 UTC, merged